### ISSUE TITLE
undefined method `bytesize' (Incompatible with latest Faraday version)

### ISSUE THREAD

**Issue by navidemad** [oauth-xx/oauth2#572]
Hi ✋🏻 

With the last update: https://github.com/oauth-xx/oauth2/compare/v1.4.7...v1.4.8

```
NoMethodError at /auth/google_oauth2/callback

undefined method `bytesize' for {"client_id"=>"**********.apps.googleusercontent.com", "client_secret"=>"*********", "grant_type"=>"authorization_code", "code"=>"********", :redirect_uri=>"http://localhost:3000/auth/google_oauth2/callback"}:Hash
    self.content_length = body.bytesize
```

<img width="1440" alt="Screenshot 2022-02-18 at 13 28 52" src="https://user-images.githubusercontent.com/6686865/154683357-ead94564-bb45-4d5a-b945-ac4a2d564f18.png">

<img width="1440" alt="Screenshot 2022-02-18 at 13 29 44" src="https://user-images.githubusercontent.com/6686865/154683350-20e90367-2b69-4ccd-acf3-fd0aa8516332.png">

**Comment by scottsherwood** [comment]
Just started seeing this same problem with the omniauth-auth0 gem too when switch from 1.4.7 to 1.4.8.

**Comment by tfader** [comment]
Same bug in case of using google auth.
NoMethodError at /auth/google_oauth2/callback

1.4.7 works for me.

**Comment by benoittgt** [comment]
It seems related to https://github.com/lostisland/faraday/issues/414#issuecomment-56123036 but I see recent code change that should fix this issue.

Like:
https://github.com/lostisland/faraday/pull/1400

**Comment by pboling** [comment]
The primary change between 1.4.7 and 1.4.8 was to allow users to upgrade to `faraday` versions `>= 2` (actually `< 3`)...  Anyone experiencing this error in a test suite, and assuming you also pulled in a faraday update, please try locking `faraday` to the previous version and keep `oauth2` at `1.4.8`.  If that resolves the error it will help diagnose a fix.

**Comment by jerryclinesmith** [comment]
Keeping `oauth2 1.4.8`, but dropping `faraday` back to < 2 (1.9.3 specifically) fixed the problem for me.

**Comment by pboling** [comment]
The fix for this issue has been in `master` branch for 4.3 years.  It is only a few lines of change.  I was hoping to get version 2 of `oauth2` out without needing to keep churning on the 1.4.x series, but haven't had time to finish v2. :(. It's 97% complete!  I was also hoping that we would not need to allow Faraday 2 upgrades in the 1.4.x series, but it creates a dependency tree snafu that is of unusual size for people who are blocked on the faraday upgrade.

I am working on backporting the fix now.
https://github.com/oauth-xx/oauth2/pull/331/files

**Comment by pboling** [comment]
If you have the time please try your test suite against the master branch.  It has a number of bug fixes / features / improvements, that are not in, and never will be in, the 1.4.x series (hundreds of commits).

**Comment by navidemad** [comment]
> The fix is now in `1-4-stable`. Please try out the branch before I release `1.4.8` if you have time.

With `gem "oauth2", github: "oauth-xx/oauth2", branch: "1-4-stable"` it works 🥇

**Comment by pboling** [comment]
Version 1.4.9 is released.  Changelog:

```
## [1.4.9] - 2022-02-20

- Fixes compatibility with Faraday v2 [572](https://github.com/oauth-xx/oauth2/issues/572)
- Includes supported versions of Faraday in test matrix:
  - Faraday ~> 2.2.0 with Ruby >= 2.6
  - Faraday ~> 1.10 with Ruby >= 2.4
  - Faraday ~> 0.17.3 with Ruby >= 1.9
- Add Windows and MacOS to test matrix
```

**Comment by pboling** [comment]
@sue445 @cratown @jerryclinesmith @dambrisco @benoittgt @tfader @scottsherwood @RSO
It should work with release 1.4.9. Please let me know if you find otherwise!

**Comment by ateras** [comment]
I maintain a small in-house developed Rails application which authenticates using OAuth against our self-hosted GitLab instance (currently running GitLab version 14.8.). I'm using Debian 11, Ruby 2.7.4 and Rails 6.0.4.4.

The versions of the relevant gems in a working configuration are:
```
oauth2 (1.4.7)
devise (4.8.1)
faraday (1.10.0)
faraday-net_http (1.0.1)
omniauth (2.0.4)
omniauth-gitlab (3.0.0)
omniauth-oauth2 (1.7.2)
omniauth-rails_csrf_protection (1.0.1)
```

If I upgrade `oauth2` to version `1.4.8`, it selects `faraday` version `2.2.0` and `faraday-net_http` version` 2.0.1` and breaks with the `undefined method 'bytesize'` error in the Rails application. Downgrading `faraday` back to `1.10.0` doesn't help.

If I upgrade `oauth2` to version `1.4.9`, it selects `faraday` version `2.2.0` and `faraday-net_http` version` 2.0.1` and breaks with a `{"error":"404 Not Found"}` message on the GitLab instance already before I get to the login screen. Downgrading `faraday` doesn't help hier either.

Looking at the nginx access log on the GitLab server gives some more information. In the working configuration with `oauth2` version `1.4.7` (and also with `oauth2` version `1.4.8`) the first request coming in looks like:
`GET /oauth/authorize?client_id=XXXXX&redirect_uri=https%3A%2F%2Four_rails_app_hostname%2Fusers%2Fauth%2Fgitlab%2Fcallback&response_type=code&scope=api&state=XXXXX HTTP/2.0` 

When using `oauth2` version `1.4.9`, the request looks like this:
`GET /api/v4/oauth/authorize?client_id=XXXXX&redirect_uri=https%3A%2F%2Four_rails_app_hostname%2Fusers%2Fauth%2Fgitlab%2Fcallback&response_type=code&scope=api&state=XXXXX HTTP/2.0`

In `config/config.yml` I have defined `gitlab_url: 'https://our_gitlab_hostname/api/v4'` as instructed in the documentation of the gem `omniauth-gitlab` (https://github.com/linchus/omniauth-gitlab/blob/v3.0.0/README.md). 

It seems that with `oauth2` version `1.4.9` and `faraday` version `2.2.0` this url gets processed differently and the `api/v4` part is included in the GET request - which actually sounds logical but doesn't work. I tried taking it out from the url defined in `config/config.yml` - then the authentication goes further, the login screen asking for username and password is shown, but the callback fails with `Undefined method '[]' for nil:nilclass` in the Rails application.

Please tell if you need any further information or have suggestions what I should try next.

**Comment by pboling** [comment]
Thanks for the update @ateras 

Based on what you've said it is clear that the issue is in the change to the request URL, which is probably caused by a change in the support for nested OAauth endpoints (which was actually a bug fix).  I'm trying to find the issue now.

**Comment by pboling** [comment]
# Related issues in 1.4.x series:

- https://github.com/oauth-xx/oauth2/issues/386
- https://github.com/oauth-xx/oauth2/issues/245
- https://github.com/oauth-xx/oauth2/issues/241
- https://github.com/oauth-xx/oauth2/pull/461

I'm not sure why the behavior changed betweeen 1.4.7-1.4.9 yet, but I do think that the configuration you had before was technically wrong, according to the OAuth spec, and according to the config, it is working correctly if it sends requests to `GET /api/v4/oauth/authorize?`, so I believe a simple config change will fix it.

# Related issues in `master` (the forthcoming v2)

- https://github.com/oauth-xx/oauth2/pull/575
- https://github.com/oauth-xx/oauth2/pull/489
- https://github.com/oauth-xx/oauth2/pull/489

**Comment by ateras** [comment]
@pboling Thank you very much for the answer!

I tried changing the configuration setting to `gitlab_url: 'https://our_gitlab_hostname/'`. In that case the authentication goes further, the GitLab login screen asking for username and password is shown, but the callback fails with `Undefined method '[]' for nil:nilclass` in the Rails application. Maybe the `omniauth-gitlab` gem (or the `devise` gem or our own app) has been relying on the old behavior and needs some corresponding small change after the bug fix.

(I'm on vacation this week and don't have access to the system right now but if I'll be happy to get back to it next week,)

**Comment by ateras** [comment]
I now upgraded `omniauth-gitlab` to the recently released version `4.0.0` and that works with `oauth2` version `1.4.9`. I think [this commit](https://github.com/linchus/omniauth-gitlab/commit/2fa1dc8bc135e3efff3d8097a814e7a50b13ebb4) fixed the issue on the side of `omniauth-gitlab`. Additionally I needed to change the configuration setting from `gitlab_url: 'https://our_gitlab_hostname/api/v4'` to `gitlab_url: 'https://our_gitlab_hostname'`.

I guess the issue can be closed now. 

For users of `omniauth-gitlab` it may still cause confusion that the configuration setting must include `/api/v4` in the `oauth2` versions up to `1.4.7` and must not include it starting from `oauth2 1.4.9` which also requires `omniauth-gitlab 4.0.0`. @pboling Do you think this is specific to `omniauth-gitlab` and the necessary change of configuration should be clarified in `omniauth-gitlab` documentation or does it also affect other gems depending on `oauth2`?

(Just for completeness: The combination of `omniauth-gitlab 4.0.0` and `oauth2 1.4.8` produced the `undefined method 'bytesize'` error but that is not very relevant as there's no reason for using version `1.4.8` instead `1.4.9` which works.)

**Comment by pboling** [comment]
Any code that relied on the bug remaining a bug is going to break, and need to be updated..

I am sure that some libraries do rely on the bug.  I think documentation in those libraries will need to be adjusted such that configurations match the correct manner of specifying the OAuth URL.

**Comment by pboling** [comment]
It is worth noting that although some libraries are affected that relied on the bug, other libraries were unable to work properly because of the bug where paths were not respected.

So this fix was imperative, and in following the OAuth spec. :)

**Comment by ateras** [comment]
Thank you @pboling! 
Just wanted to note here that I upgraded today to `oauth2 2.0.6` and also that version works in our application without problems. The `omniauth-gitlab` version stayed the same (`4.0.0`).
