### ISSUE TITLE
OAuth2::AccessToken#refresh! "NoMethodError: undefined method `options=' for nil:NilClass"

### ISSUE THREAD

**Issue by kharamel** [oauth-xx/oauth2#555]
I modified refresh token to be invalid and `refresh!` is throwing this (`NoMethodError: undefined method options=' for nil:NilClass`) error. Is it possible to throw a more semantic error similar to `raise('refresh_token is not valid')`? This way we can catch the error on our end and handle it accordingly.

Notes:
- access token is expired.
- refresh token is not expired.
- refresh token is invalid.

**Comment by rikkipitt** [comment]
My app occasionally gets the `undefined method `options=' for nil:NilClass (NoMethodError)` when refreshing. Is this due to an invalid refresh token then?

**Comment by pboling** [comment]
Great question.  If you are able to provide any additional details, or even a failing spec in a PR that would be very helpful.  I'm working on increasing spec coverage from 97.4% to 100% now.

Are you using the `1.4.x` series, or `master` branch (`2.0.x` series)?

**Comment by Exellin** [comment]
@kharamel this happens when the response doesn't contain `access_token` or `id_token` and `nil` is returned at https://github.com/oauth-xx/oauth2/blob/master/lib/oauth2/client.rb#L186.

In order to solve this issue, you need to pass in `raise_errors` as true in your options, and then this gem will turn whatever was in the response into an OAuth2::Error object which you can then rescue and handle however you wish.

**Comment by pboling** [comment]
Thanks for helping @Exellin !!
