### ISSUE TITLE
Auth code errors when posting JSON to get a token

### ISSUE THREAD

**Issue by anthony** [oauth-xx/oauth2#431]
I've searched past issues and couldn't find this one, though I feel like there may be an obvious solution.

We are using OAuth2 v1.4.0. 

The issue we are hitting is client code like this:

```
oauth_client.auth_code.get_token(
  code,
  redirect_uri: redirect_uri,
  headers: { 'Content-Type' => 'application/json' }
)
```

Is resulting in these errors coming from net/http via faraday: 

```
undefined method `bytesize' for #<Hash: ... >
```

The way I have addressed this is to add a monkey patch for now:

```
 module OAuth2
  class Client
    def get_token(params, access_token_opts = {}, access_token_class = AccessToken)
      ..snip..
      if options[:token_method] == :post
        if headers['Content-Type'] == 'application/json'
          opts[:body] = params.to_json
        else
          opts[:body] = params
        end
        opts[:headers] = {'Content-Type' => 'application/x-www-form-urlencoded'}
      else
        opts[:params] = params
        opts[:headers] = {}
      end
      ..snip..
    end
  end
end
```

Note the addition of the `if content-type == json` - other than that the original method is unchanged.

I'd be happy to provide a patch if there is no better workaround.

**Comment by pboling** [comment]
1.4.0 is not current.

Please test against 1.4.1, and then test against master, which is going to be released as 2.0.0 as soon as we can get a few more issues resolved.  Master has some mime type fixes, and I expect this has already been resolved.

**Comment by anthony** [comment]
@pboling apologies for the delay in getting back to you.

Running against master I'm hitting the same issue, but its preceded by not being able to set the header  because the params given have their keys turned to strings here: https://github.com/oauth-xx/oauth2/blob/68fac86d36a0abe65d3a656ad0dc49fe11f65fea/lib/oauth2/strategy/auth_code.rb#L30 but this code is still looking for a symbol key: https://github.com/oauth-xx/oauth2/blob/68fac86d36a0abe65d3a656ad0dc49fe11f65fea/lib/oauth2/client.rb#L134

Including the content type check added above and changing the `params.delete(:headers)` to `params.delete('headers')` gets the request sending. 

I'm not sure if its a known issue in master or not (and perhaps I'm just not using the latest version correctly so disregard if thats the case) that the client secret and id aren't added to the request body automatically anymore.

**Comment by anthony** [comment]
And 1.4.1 is exhibiting the same behaviour as 1.4.0 for me.

**Comment by pboling** [comment]
I will have to investigate.  Thanks for testing against master!  I do not currently have a way to test myself at the moment.

**Comment by will-b** [comment]
can confirm in 1.4.4

**Comment by terracatta** [comment]
Hey @pboling I'm not the original filer but I am also running into the same problem described by @anthony.

My problem is identical, the provider I am trying to sign into (a private service) requires you to POST with `application/json` instead of the standard `application/x-www-form-urlencoded` encoding. This doesn't work with the latest release (2.0.6) and I get the same `undefined method `bytesize' for #<Hash: ... >` error as the original issuer requestor.

To fix this I had to implement a monkey patch on `OAuth::Client`. Here it is below: 

```ruby
module OAuth2
  class Client
    def get_token(params, access_token_opts = {}, extract_access_token = nil, &block)
      warn('OAuth2::Client#get_token argument `extract_access_token` will be removed in oauth2 v3. Refactor to use `access_token_class` on #initialize.') if extract_access_token
      extract_access_token ||= options[:extract_access_token]
      params = params.map do |key, value|
        if RESERVED_PARAM_KEYS.include?(key)
          [key.to_sym, value]
        else
          [key, value]
        end
      end.to_h

      parse = params.key?(:parse) ? params.delete(:parse) : Response::DEFAULT_OPTIONS[:parse]
      snaky = params.key?(:snaky) ? params.delete(:snaky) : Response::DEFAULT_OPTIONS[:snaky]

      request_opts = {
        raise_errors: options[:raise_errors],
        parse: parse,
        snaky: snaky,
      }
      params = authenticator.apply(params)
      headers = params.delete(:headers) || {}
      if options[:token_method] == :post
      
        ## NEW BEHAVIOR START
        if headers[:"Content-Type"] == 'application/json'
          request_opts[:body] = params.to_json
        else
          request_opts[:body] = params
        end
        # NEW BEHAVIOR END
        
        request_opts[:headers] = {'Content-Type' => 'application/x-www-form-urlencoded'}
      else
        request_opts[:params] = params
        request_opts[:headers] = {}
      end
      request_opts[:headers].merge!(headers)
      http_method = options[:token_method]
      http_method = :post if http_method == :post_with_query_string
      response = request(http_method, token_url, request_opts, &block)

      # In v1.4.x, the deprecated extract_access_token option retrieves the token from the response.
      # We preserve this behavior here, but a custom access_token_class that implements #from_hash
      # should be used instead.
      if extract_access_token
        parse_response_with_legacy_extract(response, access_token_opts, extract_access_token)
      else
        parse_response(response, access_token_opts)
      end
    end
  end
end
```

I'm not sure if it's valid for an OAuth2 provider to require you to submit params as JSON objects, but definitely seeing more of that in the wild.

**Comment by pboling** [comment]
Interesting.  I'll look into adding support for this in the next patch release.

**Comment by pboling** [comment]
@anthony @will-b @terracatta This is fixed in 2.0.7
